updating minikube actions

diff --git a/bagan b/bagan
--- a/bagan
+++ b/bagan
@@ -1,8 +1,11 @@
 #!/bin/bash
+set -e
+
 . scripts/log.sh
 . scripts/command_helm.sh
 . scripts/command_bagan.sh
 . scripts/command_init_credentials.sh
+. scripts/command_end.sh
 
 type=$1
 mode=$2
@@ -88,46 +91,54 @@ if [ $type == "gcloud" ]; then
     eval "$(gcloudHelm)"
     eval "$(gcloudInfraPods)"
     eval "$(gcloudBagan)"
+    eval "$(endGcloud)"
   elif [ $mode == "infrastructure" ]; then
     eval "$(gcloudCredentials)"
     eval "$(gcloudHelm)"
     eval "$(gcloudInfraPods)"
     eval "$(gcloudBagan)"
+    eval "$(endGcloud)"
   elif [ $mode == "experiment" ]; then
     eval "$(gcloudCredentials)"
     eval "$(gcloudBagan)"
+    eval "$(endGcloud)"
   else
     printf '%s\n' "Error no mode parsed properly for gcloud"
     exit 1
   fi
 elif [ $type == "gcloud_docker" ]; then
   if [ $mode == "cluster" ]; then
-    execution="$(gcloudInit) $(gcloudCredentials) $(gcloudHelm) $(gcloudInfraPods) $(gcloudDockerBagan)"
+    execution="$(gcloudInit) $(gcloudCredentials) $(gcloudHelm) $(gcloudInfraPods) $(gcloudDockerBagan) $(endGcloud)"
   elif [ $mode == "infrastructure" ]; then
-    execution="$(gcloudCredentials) $(gcloudHelm) $(gcloudInfraPods) $(gcloudDockerBagan)"
+    execution="$(gcloudCredentials) $(gcloudHelmBagan) $(gcloudInfraPods) $(gcloudDockerBagan) $(endGcloud)"
   elif [ $mode == "experiment" ]; then
-    execution="$(gcloudCredentials) $(gcloudDockerBagan) "
+    execution="$(gcloudCredentials) $(gcloudDockerBagan) $(endGcloud)"
   else
     printf '%s\n' "Error no mode parsed properly for gcloud_docker"
     exit 1
   fi
-  echo $execution
   docker run -ti -v $HOME/.config/gcloud:/root/.config/gcloud \
                  -v $PWD/k8s:/usr/local/k8s \
                  -v $PWD/bagan_conf.json:/usr/local/creator/bagan_conf.json \
                     cdsap/bagan-init:0.1.1 /bin/bash -c "
                     export PATH=$PATH:/usr/local/gcloud/google-cloud-sdk/bin/;
+                    cd /usr/local;
                     $execution"
 
 elif [ $type == "minikube" ]; then
-  if [ $mode == "cluster"] || [ $mode == "infrastrucure" ]; then
-    eval "$(gcloudHelm)"
+  output=(`minikube status`)
+  if [ "${output[1]}" != "Running" ]; then
+    printf '%s\n' "Not found minikube instance with status Running"
+    exit 1
+  fi
+  if [ $mode == "cluster" ] || [ $mode == "infrastrucure" ]; then
+    eval "$(minikubeHelm)"
     eval "$(gcloudInfraPods)"
     eval "$(gcloudBagan)"
   elif [ $mode == "experiment" ]; then
     eval "$(gcloudBagan)"
   else
-    printf '%s\n' "Error no mode parsed properly for minikube"
+    printf '%s\n' "Error ;s;sno mode parsed properly for minikube"
     exit 1
   fi
 else
